Import("env")

libcgillespy3d = env.Object([
    "model.cpp",
    "model_context.cpp",
    "reaction.cpp",
    "parameter.cpp",
    "species.cpp",
    "timespan.cpp",
    "initial_condition.cpp",
    "data_function.cpp",
    "boundary_condition.cpp",
    "domain.cpp",
    "simulation.cpp",
    "error.cpp",
    # "integrator.cpp",
])

Return("libcgillespy3d")

