# action.yml
name: 'GillesPy3D Continuous Testing'
description: 'GillesPy3D Continuous Testing'
inputs:
  testin:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.testin }}
    
