env = Environment(
    CXX="g++",
    CXXFLAGS=[
        "-std=c++11",
        "-fPIC",
    ],
    CPPPATH=[
        Dir("include"),
        Dir("external/ANN/include"),
    ],
    LIBPATH=[
        Dir("obj"),
    ],
)
VariantDir("obj", "src", duplicate=False)
SConscript("obj/SConscript", exports=["env"])

# env.Program("bin/gillespy3d", ["bin/template.cpp", "bin/main.cpp"], LIBS="cgillespy3d")
