env = Environment(
    CXX="g++",
    CXXFLAGS=[
        "-std=c++17"
    ],
    CPPPATH=[
        "include",
        "external/ANN/include",
        # "external/Sundials/include",
    ],
    LIBPATH=[
        "bin"
    ],
)
VariantDir("bin", "src")
SConscript("bin/SConscript", exports=["env"])
env.Program("bin/gillespy3d", ["bin/template.cpp", "bin/main.cpp"], LIBS="cgillespy3d")
