env = Environment(
    CXX="g++",
    CXXFLAGS=[
        "-std=c++17"
    ],
    CPPPATH=[
        "include",
        "external/ANN/include",
        # "external/Sundials/include",
    ],
    LIBPATH=[
        "obj"
    ],
)
# VariantDir("obj", "src", duplicate=False)
# SConscript("src/SConscript", exports=["env"])
env.Library("cgillespy3d", [
    "src/model.cpp",
])

# env.Program("bin/gillespy3d", ["bin/template.cpp", "bin/main.cpp"], LIBS="cgillespy3d")
